name: Command output file Test

on:
  push:
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/command-output-file-action@main
        with:
          command_line: ls -lha
          output_file_name: output.txt
          display_file_content: NO
      - run: ls -lha
      - run: cat output.txt